version: "3.7"

services:
  app:
    build:
      context: ./snmp-agent
      args:
        ADMIN: ${ADMIN}
    container_name: ${CONTAINER:-container}
    restart: unless-stopped
    tty: true
    ports:
      - "${APP_PORT:-161}:161/udp"
